name: 테스트 진행. (reviewer 승인시 배포)
env:
  PORT: 3000
  DOCKER_REGISTRY: bside-front.kr.ncr.ntruss.com
  DOCKER_IMAGE: staging:latest
on:
  push:
    branches:
      - staging
    paths-ignore:
      - '**.md'

jobs:
  image-pull:
    name: Staging 서버 도커 컨테이너 적재
    runs-on: ubuntu-latest
    steps:
      - name: replace old container as latest container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY}}
          script: |
            docker rm $(docker stop $(docker ps -a -q --filter ancestor=bside-front.kr.ncr.ntruss.com/staging:latest --format="{{.ID}}"))
            docker pull bside-front.kr.ncr.ntruss.com/staging:latest
            docker run -d -p 3000:3000 --restart unless-stopped bside-front.kr.ncr.ntruss.com/staging:latest
