name: 테스트 진행. (reviewer 승인시 배포)
on:
  push:
    branches:
      - staging
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: 단위테스트 & 통합테스트 진행
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm ci
      - run: npm run test:ci

  deployment:
    name: Staging 서버 배포
    needs: test
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCP Registry
        uses: docker/login-action@v2
        with:
          registry: bside-front.kr.ncr.ntruss.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # -
      #   name: staging 빌드를 위한 .env.staging 파일 생성
      #   run: |
      #     echo "REACT_APP_ENV=staging" >> .env.staging
      #     echo "REACT_APP_SOME_VALUE=$REACT_APP_SOME_VALUE" >> .env.staging
      #   env:
      #     REACT_APP_SOME_VALUE: ${{ secrets.REACT_APP_SOME_VALUE }}
      #

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: bside-front.kr.ncr.ntruss.com/staging:latest
